version: "3.8"

services:
  reverse-proxy:
    environment:
      - DJANGO_WSGI=django-asgi:8000

  streaming:
    ports:
      - 8081:1985 # HTTP API server, for HTTP-API, WebRTC.

  django-asgi: &app
    image: online-events/app-dev
    build:
      context: ./app
      target: dev
    entrypoint: ./entrypoints/entrypoint-dev.sh
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/.venv
    environment:
      - DJANGO_DEBUG=True

  django-wsgi:
    deploy:
      replicas: 0

  celery-worker:
    <<: *app
    entrypoint: ./entrypoints/entrypoint-dev-celery.sh

  celery-beat:
    deploy:
      replicas: 0
