version: "3.8"

services:
  nginx:
    environment:
      - DJANGO_WSGI=django-asgi:8000

  django-asgi:
    build:
      context: ./app
      target: dev
    entrypoint: ./entrypoint-dev.sh
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/.venv
    environment:
      - DJANGO_DEBUG=True

  django-wsgi:
    deploy:
      replicas: 0
