# Generated by Django 4.1.7 on 2023-08-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0008_remove_authtoken_salt'),
        ('users', '0003_chatkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStreamKey',
            fields=[
                ('authtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knox.authtoken')),
            ],
            bases=('knox.authtoken',),
        ),
    ]
