# Generated by Django 4.1.7 on 2023-08-18 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("knox", "0008_remove_authtoken_salt"),
        ("users", "0004_playstreamkey"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationKey",
            fields=[
                (
                    "authtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="knox.authtoken",
                    ),
                ),
            ],
            bases=("knox.authtoken",),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
