# Generated by Django 4.1.7 on 2023-07-04 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_attendees_alter_event_organizer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("-started_at",)},
        ),
        migrations.AddField(
            model_name="event",
            name="started_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 4, 20, 55, 34, 294342, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
