# Generated by Django 4.1.7 on 2023-08-18 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0003_alter_event_options_event_started_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="booked_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
